services:
  postgres:
    container_name: postgres_physicare
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    # volumes:
    #   - postgres:/var/lib/postgresql/data:rw
